### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ghost** [patrickcjk/imgui-notify#1]
I get the following error when I try to call notify::init() after ImGui_ImplDX12_Init()

 ![image](https://user-images.githubusercontent.com/45088542/124243887-38278200-dad3-11eb-9cac-b00462ef064f.png)

I included all the files correctly and am doing exactly as the instructions stated. It seems its failing to initialize the font... What is going on here?

**Comment by ghost** [comment]
Are you possibly able to provide me with src to a working imgui example or something with these notifications built in? I dont know how to fix these issues sadly (Great project btw!)

**Comment by patrickcjk** [comment]
Have a look to the example i just pushed.

**Comment by ghost** [comment]
Working now. Thanks very much!
