### ISSUE TITLE
Errors with success, warning, error, info

### ISSUE THREAD

**Issue by GamebP** [patrickcjk/imgui-notify#12]
![image](https://user-images.githubusercontent.com/88152063/179360053-d1a1fc45-52a7-4ef5-8a9d-aa081fb4c425.png)

**Comment by GamebP** [comment]
give me even more errors when i put (char*)"Success"; and to each of them. then i compile, then i get icon erros all over in the .h file. 
was using Release x86 with multibytes

**Comment by rxvan** [comment]
> give me even more errors when i put (char*)"Success"; and to each of them. then i compile, then i get icon erros all over in the .h file. was using Release x86 with multibytes

change to const char*
