### ISSUE TITLE
C4703	potentially uninitialized local pointer variable 'icon' used

### ISSUE THREAD

**Issue by irizkyw** [patrickcjk/imgui-notify#16]
compiling failure cause in imgui_notify.h
![image](https://user-images.githubusercontent.com/78690451/203515125-8e23697d-274c-49c2-9ff2-c1b56a36732a.png)

how to fix it?

**Comment by 333testing** [comment]
`NOTIFY_INLINE auto get_icon() -> const char*`

**Comment by irizkyw** [comment]
NOTIFY_INLINE auto get_icon() -> const char* is already used but I'm calling function ImGui::RenderNotifications(); in main.cpp still getting the same error

![image](https://user-images.githubusercontent.com/78690451/205447441-9e2bce55-e698-47b7-9583-243f80a4ce98.png)

**Comment by enesahn** [comment]
> NOTIFY_INLINE auto get_icon() -> const char*

did you solve this error ?

**Comment by irizkyw** [comment]
> 

nope sir

**Comment by SandFoxy** [comment]
ChatGPT Helps me just add 
`#pragma warning(disable: 4703)
#pragma warning(default: 4703)
`
