### ISSUE TITLE
rendering the notifications in the external overlay not in HWND

### ISSUE THREAD

**Issue by 333testing** [patrickcjk/imgui-notify#17]
this happens because it renders in HWND:
![image](https://user-images.githubusercontent.com/119223928/204151972-a4025dc5-ea29-4cc6-bf40-7f40567de0c7.png)

if someone have the solution please lmk!

**Comment by AmpedWasTaken** [comment]
i need this to

**Comment by 333testing** [comment]
> i need this to

i fixed it!

**Comment by ImDarkyz** [comment]
> i fixed it!

Could you share the fix?
