### ISSUE TITLE
NOTIFY_FORMAT doesn't compile

### ISSUE THREAD

**Issue by caxapexac** [patrickcjk/imgui-notify#6]
i.e.

```cpp
imgui_notify.h:205:83: error: expected expression
    ImGuiToast(ImGuiToastType type, const char* format, ...) : ImGuiToast(type) { NOTIFY_FORMAT(this->set_content, format); }

imgui_notify.h:23:120: note: expanded from macro 'NOTIFY_FORMAT'
#define NOTIFY_FORMAT(fn, format, ...)  if (format) { va_list args; va_start(args, format); fn(format, args, __VA_ARGS__); va_end(args); }
```

That's what my clangd 14.0.0 says
![image](https://user-images.githubusercontent.com/33996246/147409090-5a147ee4-5145-44e2-a6e7-39e87c9bb2d5.png)

Clangd config: -Wno-unused-variable,-Wno-infinite-recursion,-Werror=implicit-function-declaration,-Wshadow,-Wno-shadow-field-in-constructor-modified,-Wno-shadow-ivar,-Wuninitialized,-Wunused-label,-Wunused-lambda-capture, ,--target=aarch64

**Comment by caxapexac** [comment]
Seems like VA_ARGS dont exist in expanded macro

**Comment by OrchaHax** [comment]
Did you ever fix this?

**Comment by caxapexac** [comment]
@OrchaHax try to remove this comma in macro declaration
![image](https://user-images.githubusercontent.com/33996246/164886951-c891c109-66d0-4a70-af6a-9b0237223bad.png)

```cpp
#define NOTIFY_FORMAT(fn, format, ...)	if (format) { va_list args; va_start(args, format); fn(format, args); va_end(args); }
```

**Comment by caxapexac** [comment]
Okay its dead
